services:
  fastxyz:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastxyz
    restart: unless-stopped
    ports:
      - 3003:3000
    environment:
      - TZ=Australia/Melbourne
      - TIINGO_API_KEY=abc123
    volumes:
      - ./src/data:/app/src/data
    network_mode: bridge
