services:
  fastxyz:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastxyz
    restart: unless-stopped
    ports:
      - 3003:3000
    environment:
      - TZ=
      - TIINGO_API_KEY=
      - API_KEY=
    volumes:
      - ./src/data:/app/src/data
    network_mode: bridge
